apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-service-config
  namespace: nmap-ui
data:
  config.yaml: |
    app:
      name: scanner-service
      version: 0.1.0

    server:
      http:
        port: 8081
        timeout: 30s
        read_timeout: 15s
        write_timeout: 15s
      grpc:
        port: 9081
        timeout: 30s

    nmap:
      path: nmap
      timeout: 300s
      max_concurrent_scans: 5

    log:
      level: info
      format: json
      output: stdout

    storage:
      type: memory
      retention_period: 168h