apiVersion: v1
kind: Service
metadata:
  name: scanner-service
  namespace: nmap-ui
  labels:
    app: scanner-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 9081
      targetPort: 9081
      protocol: TCP
      name: grpc
  selector:
    app: scanner-service